services:
  redis:
    image: redis:8-alpine
    profiles:
      - db
      - all
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal_network

  editor:
    image: pob-91/telegram-spreadsheet-editor:latest
    profiles:
      - all
    ports:
      - "8080:8080"
    env_file:
      # Use .env.example to create a .env file and load it here
      - .env
    networks:
      - internal_network

networks:
  internal_network:
    name: internal_network
