services:
  redis:
    image: redis:8-alpine
    profiles:
      - db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal_network

  editor:
    image: spreadsheet-editor:latest
    profiles:
      - all
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=localhost:6379
      # Add other env vars from .env.example here as required
    networks:
      - internal_network

networks:
  internal_network:
    name: internal_network
